
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tlbygdxblfpqnheqsuzw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRsYnlnZHhibGZwcW5oZXFzdXp3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI2MzEwMTEsImV4cCI6MjA1ODIwNzAxMX0.bAddhrdShtjK0wbGuP7B1wf1XFUsZJzy1prYyiXi8as";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
